server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized

csneps:
  host: localhost
  port: 50051     # CSNePS gRPC server port
  
grpc:
  port: 50061

logging:
  level:
    com.csri: DEBUG
    io.grpc: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
