name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build CSNePS Core
      run: |
        docker build -f docker/Dockerfile.csneps -t csneps-core .

    - name: Build Python Adapters
      run: |
        docker build -f docker/Dockerfile.python -t python-adapters .

    - name: Run integration tests
      run: |
        docker-compose -f docker/compose.yaml up --build --abort-on-container-exit

    - name: Clean up
      run: |
        docker-compose -f docker/compose.yaml down
