name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=tag
          type=raw,value=latest

    - name: Build and push CSNePS Core
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.csneps
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Python Adapters
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/Dockerfile.python
        push: true
        tags: ghcr.io/${{ github.repository }}-python:${{ steps.meta.outputs.version }}
        labels: ${{ steps.meta.outputs.labels }}
